all:
  vars:
    ansible_user: lab
    ansible_python_interpreter: /usr/bin/python3

  children:
    provider:
      hosts:
        isp-core1:
          ansible_host: 192.168.1.61
        isp-core2:
          ansible_host: 192.168.1.62
        pe1:
          ansible_host: 192.168.1.63

    customer:
      hosts:
        ce1:
          ansible_host: 192.168.1.64

    services:
      hosts:
        svc1:
          ansible_host: 192.168.1.131
        media1:
          ansible_host: 192.168.1.50